#!/usr/bin/env -S nix develop .#update -c bash

COMMIT="$1"
ROOT_DIR="$(pwd)"

git_push() {
    if [[ "$COMMIT" == "--commit" ]]; then
        (
            cd "$ROOT_DIR" || return
            git config --global user.name 'Updater'
            git config --global user.email 'robot@nowhere.invalid'
            git remote update

            alejandra .
            git add .

            git commit -m "$1"
            git push
        )
    else
        echo "$1"
    fi
}

updateNpmDepsHash() {
    file="$ROOT_DIR/pkgs/jellyfin-web/npmDepsHash.nix"
    npm_hash="$(nix build .#jellyfin-web |& sed -n 's/.*got: *//p')"

    if [[ "$npm_hash" != "" ]]; then
        {
            echo '# This file was autogenerated. DO NOT EDIT!'
            echo "\"$npm_hash\""
        } >"$file"

        echo "updated npmDepsHash"
    else
        echo "npmDepsHash is already up to date"
    fi
}

updateNugetDeps() {
    $(nix build .#jellyfin.fetch-deps --print-out-paths --no-link) "$ROOT_DIR/pkgs/jellyfin/nuget-deps.nix"
}

updatePackage() {
    nix flake update

    owner="$1"
    repo="$2"
    file="$ROOT_DIR/pkgs/$repo/src.nix"

    current_version=$(nix eval --json --file "$file" | jq -r .rev)
    new_version=$(curl -s "https://api.github.com/repos/$owner/$repo/releases/latest" | jq -r .tag_name)

    if [[ "$new_version" != "null" && "$new_version" != "$current_version" ]]; then
        hash=$(nix-prefetch-github "$owner" "$repo" --rev "$new_version" | jq -r .hash)

        {
            echo '# This file was autogenerated. DO NOT EDIT!'
            echo '{'
            echo "  owner = \"$owner\";"
            echo "  repo = \"$repo\";"
            echo "  rev = \"$new_version\";"
            echo "  hash = \"$hash\";"
            echo '}'
        } >"$file"

        # Update third party sources
        if [[ "$repo" == "jellyfin-web" ]]; then
            updateNpmDepsHash
        elif [[ "$repo" == "jellyfin" ]]; then
            updateNugetDeps
        fi

        git_push "ci: $repo ${current_version#v} -> ${new_version#v}"
    else
        echo "$repo is already up to date"
    fi
}

updatePackage "jellyfin" "jellyfin"
updatePackage "jellyfin" "jellyfin-web"
updatePackage "jellyfin" "jellyfin-ffmpeg"
updatePackage "jellyfin" "jellyfin-media-player"
