name: "build"
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30

    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: jellyfin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: build
      run: nix develop .#build -c buildAll
